# Generated by Django 4.1.3 on 2022-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_name_people_nam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='people',
            name='nam',
            field=models.CharField(max_length=300),
        ),
    ]
